### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by ggebbie** [ggebbie/GH19.jl#3]
- [x] extract timeseries at any grid point

       1. `using https://github.com/ggebbie/TMI.jl`
       2. read just one time snapshot at any time
       3. save as a `Vector{}`: (can be Float32?)

- [x] extract timeseries at any location, nothing if land, interpolate to point if wet

             1. read one snapshot at a time
             2. use `TMI.observe` to pick a sample point https://github.com/ggebbie/TMI.jl/blob/9ef4ce01f89713a757b6e83ce7ea12f9c700f735/src/TMI.jl#L1329
             3. use observe like this function https://github.com/ggebbie/TMI.jl/blob/9ef4ce01f89713a757b6e83ce7ea12f9c700f735/src/TMI.jl#L1273 

- [x] handle (-t)-z-y-x convention for 4D file contents

- [ ] compute global ocean heat content using some TMI utilities

                  1.         get volume from `volumefilled` function https://github.com/ggebbie/TMI.jl/blob/9ef4ce01f89713a757b6e83ce7ea12f9c700f735/src/TMI.jl  
                  2.   can approximate density
                  3. later think about adding GibbsSeaWater.jl for density
                  4. use `\gamma.wet` mask to make sums without searching for NaNs    \
                  5. example script `ex5.surfaceorigin.jl`:   https://github.com/ggebbie/TMI.jl/blob/9ef4ce01f89713a757b6e83ce7ea12f9c700f735/src/TMI.jl

- [ ] compute regional ocean heat content using masks/basin info, etc.
                  1. TMI has surface boundary masks, use for interior ocean?
                  2. example is function `surfaceregion` https://github.com/ggebbie/TMI.jl/blob/9ef4ce01f89713a757b6e83ce7ea12f9c700f735/src/TMI.jl#L163

- [ ] transfer ocean heat content to heat convergence and effective planetary heat flux
- [ ] ...

**Comment by anthony-meza** [comment]
Addressed Items 1-3 in my branch [here](https://github.com/ggebbie/GH19.jl/blob/cc2fffc9d1af36989a00b87684379bf3ac8fa41a/test/interpolations_4D.jl)

One issue with my solution is that it relies on the Field struct, which only accepts "tracer" fields of Array{T, 3}. Likely inefficient. Can we extend tracers to Array{T, N}?

**Comment by ggebbie** [comment]
thank you, @anthony-meza!  I'm happy to make an update. Is this a change to be made in a dependency somewhere? What is the case with 4+ dimensional arrays? When time is added as a dimension?

**Comment by anthony-meza** [comment]
@ggebbie The change to the Field struct would have to be made in TMI.jl. Yes, the case with 4D arrays arises when time is added as a dimension as in GH19.jl.
